[package]
name = "my-desire-macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "impl details of my-desire"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
